### PR TITLE
Add alarms to rails elixir

### PR DESCRIPTION
**Pull request by chrisghill**

### CODE REVIEW

**Review by likelymichael — APPROVED** [review]

**Review by coryodaniel — CHANGES_REQUESTED** [review]
These charts are designed to be massdriver-agnostic. See [here](https://github.com/massdriver-cloud/helm-charts/tree/main/charts/ruby-on-rails#sponsor)

**Comment by chrisghill** [comment]
> These charts are designed to be massdriver-agnostic. See [here](https://github.com/massdriver-cloud/helm-charts/tree/main/charts/ruby-on-rails#sponsor)

By default it doesn't install the dependencies. The `enabled` field defaults to `false`. See [here](https://github.com/massdriver-cloud/helm-charts/pull/7/files#diff-4d3fb57aeaf46dc5b66f7512cf5f14fcf4e92d6db2832b83587643ef5b9be07aR45). Many helm charts "optionally" install things like prometheus service monitors conditionally. I would argue that doesn't make them "dependent" on prometheus. Its a convenient toggle to enable additional capabilities if the cluster supports it.

But we can also install it separately w/ the standalone terraform module: https://github.com/massdriver-cloud/terraform-modules/tree/main/k8s/alarm-channel

**Comment by coryodaniel** [comment]
I think it’s confusing to any end users that find these charts in ArtifactHub as MD will show up as a dependency. 

We should add support for addl functionality through our app templates repo. Also that way we don’t have to make massdriver changes in two places. Keep it all in the MD specific repo. 

Alternatively if we can make these other charts good generic charts, I think we can include them. What’s MD specific about either? Just the URL alarms are delivered to?

**Comment by chrisghill** [comment]
> Alternatively if we can make these other charts good generic charts, I think we can include them. What’s MD specific about either? Just the URL alarms are delivered to?

The main thing is that the "values.yaml" is structured match our JSON schema structure rather than to the actual k8s manifest structure. This is particularly true for ingress stuff, but a couple others are a little different as well.

So in some sense its optimized for a UI interaction instead of optimized for helm chart consistency/maintenance.

**Comment by coryodaniel** [comment]
Adding via app templates!

**Pull request merged**
